// <auto-generated />
using FilmCollectionAssignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollectionAssignment.Migrations
{
    [DbContext(typeof(FilmAdditions))]
    partial class FilmAdditionsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("FilmCollectionAssignment.Models.AddFilm", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmId");

                    b.ToTable("addFilms");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Dark Knight",
                            Year = (ushort)2008
                        },
                        new
                        {
                            FilmId = 2,
                            Category = "RomCom",
                            Director = "Damien Chazelle",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "la La Land",
                            Year = (ushort)2016
                        },
                        new
                        {
                            FilmId = 3,
                            Category = "Action/Adventure",
                            Director = "David Yates",
                            Edited = false,
                            Rating = "PG",
                            Title = "Harry Potter and the Half-Blood Prince",
                            Year = (ushort)2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
